title: "Population Evolution by Age Groups in Latin America (2000-20"
description: "This dataset contains data on the population evolution by age groups in 11 Latin American countries for the years 2000, 2010, 2020 and 2023. Countries"
author: "Juan Moisés de la Serna Tuya"
url: "https://juanmoisesd.github.io"
baseurl: "/population-evolution-by-age-groups-in-latin-america-2000-2023-dataset-by-country"
